import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { StoreWrapper } from "./store/store-wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreWrapper>
          <main className="flex min-h-screen font-mono flex-col items-center justify-start bg-gradient-to-br from-sky-500 via-purple-500 to-orange-500 animate-bg-animate">
            <h1 className="shadow-xl bg-purple-800/15 rounded-3xl flex justify-center p-6 m-6 text-5xl font-mono font-bold text-white z-10">{`<PokEmerson 🐣/>`}</h1>
            {children}
          </main>
        </StoreWrapper>
      </body>
    </html>
  );
}
